### ISSUE TITLE
Latest Docker Version of Director Broken: 0.2.0-31-g84b848a

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/ota-community-edition#59]
The latest docker image(0.2.0-31-g84b848a) breaks at boot. This doesn't happen under 0.2.0-29-g68a1fa1. Here's the stack trace:
~~~
E|21:36:48.401|com.advancedtelematic.director.Boot$|Invalid service configuration: NonEmptyList(DecodingFailure at .ats.metricsReporter.reportMetrics: Boolean)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.advancedtelematic.director.Boot.main(Boot.scala)
Caused by: java.lang.Throwable: Invalid service configuration: NonEmptyList(DecodingFailure at .ats.metricsReporter.reportMetrics: Boolean)
	at com.advancedtelematic.director.Settings.$anonfun$metricsReporterSettings$6(Boot.scala:60)
	at cats.data.Validated.fold(Validated.scala:14)
	at com.advancedtelematic.director.Settings.$init$(Boot.scala:61)
	at com.advancedtelematic.director.Boot$.<init>(Boot.scala:66)
	at com.advancedtelematic.director.Boot$.<clinit>(Boot.scala)
~~~

**Comment by doanac** [comment]
This is now fixed with the latest container: 0.2.0-35-gd04f6f6
